from PyQt6 import QtCore, QtWidgets 
from PyQt6.QtCore import QFileSystemWatcher
from PyQt6.QtGui import QIntValidator,QIcon
import os
from backend import clase_funciones
current_dir = os.getcwd()
img_path = os.path.join(current_dir, "Imagenes","")
included_extensions = ['JPG','jpg','jpeg', 'bmp','PNG', 'png', 'gif','',' ']
file_names = [fn for fn in os.listdir(img_path)
    if any(fn.endswith(ext) for ext in included_extensions)]

if not os.path.exists(img_path):
    os.makedirs(img_path)



class Ui_Buscador(QtWidgets.QWidget, QtCore.QObject):
    def __init__(self):
        super().__init__()
        self.funciones = clase_funciones(self)  



    def setupUi(self, Buscador):
        Buscador.setObjectName("Buscador")
        Buscador.resize(490, 324)
        self.gridLayout = QtWidgets.QGridLayout(Buscador)
        self.gridLayout.setObjectName("gridLayout")
        self.lyt_main = QtWidgets.QVBoxLayout()
        self.lyt_main.setObjectName("lyt_main")
        self.lyt_up_pos = QtWidgets.QHBoxLayout()
        self.lyt_up_pos.setObjectName("lyt_up_pos")
        self.lyt_posicion_select = QtWidgets.QVBoxLayout()
        self.lyt_posicion_select.setContentsMargins(5, 6, 5, 6)
        self.lyt_posicion_select.setSpacing(6)
        self.lyt_posicion_select.setObjectName("lyt_posicion_select")
        self.cb_posicion = QtWidgets.QComboBox(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_posicion.sizePolicy().hasHeightForWidth())
        self.cb_posicion.setSizePolicy(sizePolicy)
        self.cb_posicion.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.cb_posicion.setObjectName("cb_posicion")
        self.cb_posicion.addItem("")
        self.cb_index=self.cb_posicion.currentIndex()

        self.lyt_posicion_select.addWidget(self.cb_posicion)
        self.lyt_pos_inicial_2 = QtWidgets.QHBoxLayout()
        self.lyt_pos_inicial_2.setObjectName("lyt_pos_inicial_2")
        self.lblno_top_left_inicial = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_top_left_inicial.sizePolicy().hasHeightForWidth())
        self.lblno_top_left_inicial.setSizePolicy(sizePolicy)
        self.lblno_top_left_inicial.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblno_top_left_inicial.setObjectName("lblno_top_left_inicial")
        self.lyt_pos_inicial_2.addWidget(self.lblno_top_left_inicial)
        self.lblno_top_leftx = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_top_leftx.sizePolicy().hasHeightForWidth())
        self.lblno_top_leftx.setSizePolicy(sizePolicy)
        self.lblno_top_leftx.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblno_top_leftx.setObjectName("lblno_top_leftx")
        self.lyt_pos_inicial_2.addWidget(self.lblno_top_leftx)
        self.txtno_top_left_x = QtWidgets.QLineEdit(parent=Buscador)
        self.txtno_top_left_x.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtno_top_left_x.sizePolicy().hasHeightForWidth())
        self.txtno_top_left_x.setSizePolicy(sizePolicy)
        self.txtno_top_left_x.setInputMask("")
        self.txtno_top_left_x.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtno_top_left_x.setObjectName("txtno_top_left_x")
        self.lyt_pos_inicial_2.addWidget(self.txtno_top_left_x)
        self.lblno_top_lefty = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_top_lefty.sizePolicy().hasHeightForWidth())
        self.lblno_top_lefty.setSizePolicy(sizePolicy)
        self.lblno_top_lefty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblno_top_lefty.setObjectName("lblno_top_lefty")
        self.lyt_pos_inicial_2.addWidget(self.lblno_top_lefty)
        self.txtno_top_left_y = QtWidgets.QLineEdit(parent=Buscador)
        self.txtno_top_left_y.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtno_top_left_y.sizePolicy().hasHeightForWidth())
        self.txtno_top_left_y.setSizePolicy(sizePolicy)
        self.txtno_top_left_y.setInputMask("")
        self.txtno_top_left_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtno_top_left_y.setObjectName("txtno_top_left_y")
        self.lyt_pos_inicial_2.addWidget(self.txtno_top_left_y)
        self.lyt_posicion_select.addLayout(self.lyt_pos_inicial_2)
        self.lyt_pos_final_2 = QtWidgets.QHBoxLayout()
        self.lyt_pos_final_2.setObjectName("lyt_pos_final_2")
        self.lblno_bot_right_final = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_bot_right_final.sizePolicy().hasHeightForWidth())
        self.lblno_bot_right_final.setSizePolicy(sizePolicy)
        self.lblno_bot_right_final.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblno_bot_right_final.setObjectName("lblno_bot_right_final")
        self.lyt_pos_final_2.addWidget(self.lblno_bot_right_final)
        self.lblno_bot_rightx = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_bot_rightx.sizePolicy().hasHeightForWidth())
        self.lblno_bot_rightx.setSizePolicy(sizePolicy)
        self.lblno_bot_rightx.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblno_bot_rightx.setObjectName("lblno_bot_rightx")
        self.lyt_pos_final_2.addWidget(self.lblno_bot_rightx)
        self.txtno_bot_right_x = QtWidgets.QLineEdit(parent=Buscador)
        self.txtno_bot_right_x.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtno_bot_right_x.sizePolicy().hasHeightForWidth())
        self.txtno_bot_right_x.setSizePolicy(sizePolicy)
        self.txtno_bot_right_x.setInputMask("")
        self.txtno_bot_right_x.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtno_bot_right_x.setObjectName("txtno_bot_right_x")
        self.lyt_pos_final_2.addWidget(self.txtno_bot_right_x)
        self.lblno_bot_righty = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_bot_righty.sizePolicy().hasHeightForWidth())
        self.lblno_bot_righty.setSizePolicy(sizePolicy)
        self.lblno_bot_righty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblno_bot_righty.setObjectName("lblno_bot_righty")
        self.lyt_pos_final_2.addWidget(self.lblno_bot_righty)
        self.txtno_bot_right_y = QtWidgets.QLineEdit(parent=Buscador)
        self.txtno_bot_right_y.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtno_bot_right_y.sizePolicy().hasHeightForWidth())
        self.txtno_bot_right_y.setSizePolicy(sizePolicy)
        self.txtno_bot_right_y.setInputMask("")
        self.txtno_bot_right_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtno_bot_right_y.setObjectName("txtno_bot_right_y")
        self.lyt_pos_final_2.addWidget(self.txtno_bot_right_y)
        self.lyt_posicion_select.addLayout(self.lyt_pos_final_2)
        
        
        
        self.lyt_confidence_2 = QtWidgets.QHBoxLayout()
        self.lyt_confidence_2.setObjectName("lyt_confidence_2")
        self.lblno_confidence = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblno_confidence.sizePolicy().hasHeightForWidth())
        self.lblno_confidence.setSizePolicy(sizePolicy)
        self.lblno_confidence.setObjectName("lblno_confidence")
        self.lyt_confidence_2.addWidget(self.lblno_confidence)
        self.txtno_confidence = QtWidgets.QLineEdit(parent=Buscador)
        self.txtno_confidence.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtno_confidence.sizePolicy().hasHeightForWidth())
        self.txtno_confidence.setSizePolicy(sizePolicy)
        self.txtno_confidence.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txtno_confidence.setObjectName("txtno_confidence")
        self.lyt_confidence_2.addWidget(self.txtno_confidence)
        self.lyt_posicion_select.addLayout(self.lyt_confidence_2)
        
        
        self.lyt_up_pos.addLayout(self.lyt_posicion_select)
        self.lyt_op_posiciones = QtWidgets.QVBoxLayout()
        self.lyt_op_posiciones.setContentsMargins(5, 0, 5, 0)
        self.lyt_op_posiciones.setObjectName("lyt_op_posiciones")
        self.btn_add_pos = QtWidgets.QPushButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_pos.sizePolicy().hasHeightForWidth())
        self.btn_add_pos.setSizePolicy(sizePolicy)
        self.btn_add_pos.setObjectName("btn_add_pos")
        self.lyt_op_posiciones.addWidget(self.btn_add_pos)
        self.btn_mod_pos = QtWidgets.QPushButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mod_pos.sizePolicy().hasHeightForWidth())
        self.btn_mod_pos.setSizePolicy(sizePolicy)
        self.btn_mod_pos.setObjectName("btn_mod_pos")
        self.lyt_op_posiciones.addWidget(self.btn_mod_pos)
        self.btn_remover = QtWidgets.QPushButton(parent=Buscador)
        self.btn_remover.setObjectName("btn_remover")
        self.lyt_op_posiciones.addWidget(self.btn_remover)
        self.lyt_up_pos.addLayout(self.lyt_op_posiciones)
        self.lyt_pos_info = QtWidgets.QVBoxLayout()
        self.lyt_pos_info.setContentsMargins(5, -1, 5, -1)
        self.lyt_pos_info.setObjectName("lyt_pos_info")
        self.lyt_nombre = QtWidgets.QHBoxLayout()
        self.lyt_nombre.setObjectName("lyt_nombre")
        self.lbl_nombre = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_nombre.sizePolicy().hasHeightForWidth())
        self.lbl_nombre.setSizePolicy(sizePolicy)
        self.lbl_nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lyt_nombre.addWidget(self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_nombre.sizePolicy().hasHeightForWidth())
        self.txt_nombre.setSizePolicy(sizePolicy)
        self.txt_nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_nombre.setObjectName("txt_nombre")
        self.lyt_nombre.addWidget(self.txt_nombre)
        self.lyt_pos_info.addLayout(self.lyt_nombre)
        self.lyt_pos_inicial = QtWidgets.QHBoxLayout()
        self.lyt_pos_inicial.setObjectName("lyt_pos_inicial")
        self.lbl_top_left_inicial = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_top_left_inicial.sizePolicy().hasHeightForWidth())
        self.lbl_top_left_inicial.setSizePolicy(sizePolicy)
        self.lbl_top_left_inicial.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_top_left_inicial.setObjectName("lbl_top_left_inicial")
        self.lyt_pos_inicial.addWidget(self.lbl_top_left_inicial)
        
        self.btn_inicial = QtWidgets.QPushButton(parent=Buscador)
        self.btn_inicial.setText("")
        self.btn_inicial.setObjectName("btn_inicial")
        self.btn_inicial.setIcon(QIcon("crosshair.png"))
        self.lyt_pos_inicial.addWidget(self.btn_inicial)
        self.lbl_top_leftx = QtWidgets.QLabel(parent=Buscador)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_top_leftx.sizePolicy().hasHeightForWidth())
        self.lbl_top_leftx.setSizePolicy(sizePolicy)
        self.lbl_top_leftx.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_top_leftx.setObjectName("lbl_top_leftx")
        self.lyt_pos_inicial.addWidget(self.lbl_top_leftx)
        self.txt_top_left_x = QtWidgets.QLineEdit(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_top_left_x.sizePolicy().hasHeightForWidth())
        self.txt_top_left_x.setSizePolicy(sizePolicy)
        self.txt_top_left_x.setInputMask("")
        self.txt_top_left_x.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_top_left_x.setObjectName("txt_top_left_x")
        self.txt_top_left_x.setValidator(QIntValidator(0,9999))
        self.lyt_pos_inicial.addWidget(self.txt_top_left_x)
        self.lbl_top_lefty = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_top_lefty.sizePolicy().hasHeightForWidth())
        self.lbl_top_lefty.setSizePolicy(sizePolicy)
        self.lbl_top_lefty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_top_lefty.setObjectName("lbl_top_lefty")
        self.lyt_pos_inicial.addWidget(self.lbl_top_lefty)
        self.txt_top_left_y = QtWidgets.QLineEdit(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_top_left_y.sizePolicy().hasHeightForWidth())
        self.txt_top_left_y.setSizePolicy(sizePolicy)
        self.txt_top_left_y.setInputMask("")
        self.txt_top_left_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_top_left_y.setObjectName("txt_top_left_y")
        self.txt_top_left_y.setValidator(QIntValidator(0,9999))
        self.lyt_pos_inicial.addWidget(self.txt_top_left_y)
        self.lyt_pos_info.addLayout(self.lyt_pos_inicial)
        self.lyt_pos_final = QtWidgets.QHBoxLayout()
        self.lyt_pos_final.setObjectName("lyt_pos_final")
        self.lbl_bot_right_final = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_bot_right_final.sizePolicy().hasHeightForWidth())
        self.lbl_bot_right_final.setSizePolicy(sizePolicy)
        self.lbl_bot_right_final.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_bot_right_final.setObjectName("lbl_bot_right_final")
        self.lyt_pos_final.addWidget(self.lbl_bot_right_final)
        self.lbl_bot_rightx = QtWidgets.QLabel(parent=Buscador)
        
        self.btn_final = QtWidgets.QPushButton(parent=Buscador)
        self.btn_final.setText("")
        self.btn_final.setObjectName("btn_final")
        self.btn_final.setIcon(QIcon("crosshair.png"))

        self.lyt_pos_final.addWidget(self.btn_final)
        
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_bot_rightx.sizePolicy().hasHeightForWidth())
        self.lbl_bot_rightx.setSizePolicy(sizePolicy)
        self.lbl_bot_rightx.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_bot_rightx.setObjectName("lbl_bot_rightx")
        self.lyt_pos_final.addWidget(self.lbl_bot_rightx)
        self.txt_bot_right_x = QtWidgets.QLineEdit(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_bot_right_x.sizePolicy().hasHeightForWidth())
        self.txt_bot_right_x.setSizePolicy(sizePolicy)
        self.txt_bot_right_x.setInputMask("")
        self.txt_bot_right_x.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_bot_right_x.setObjectName("txt_bot_right_x")
        self.txt_bot_right_x.setValidator(QIntValidator(0,9999))
        self.lyt_pos_final.addWidget(self.txt_bot_right_x)
        self.lbl_bot_righty = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_bot_righty.sizePolicy().hasHeightForWidth())
        self.lbl_bot_righty.setSizePolicy(sizePolicy)
        self.lbl_bot_righty.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_bot_righty.setObjectName("lbl_bot_righty")
        self.lyt_pos_final.addWidget(self.lbl_bot_righty)
        self.txt_bot_right_y = QtWidgets.QLineEdit(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_bot_right_y.sizePolicy().hasHeightForWidth())
        self.txt_bot_right_y.setSizePolicy(sizePolicy)
        self.txt_bot_right_y.setInputMask("")
        self.txt_bot_right_y.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_bot_right_y.setObjectName("txt_bot_right_y")
        self.txt_bot_right_y.setValidator(QIntValidator(0,9999))
        self.lyt_pos_final.addWidget(self.txt_bot_right_y)
        
        
        self.lyt_pos_info.addLayout(self.lyt_pos_final)
        self.lyt_confidence = QtWidgets.QHBoxLayout()
        self.lyt_confidence.setObjectName("lyt_confidence")
        self.lbl_confidence = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_confidence.sizePolicy().hasHeightForWidth())
        self.lbl_confidence.setSizePolicy(sizePolicy)
        self.lbl_confidence.setObjectName("lbl_confidence")
        self.lyt_confidence.addWidget(self.lbl_confidence)
        self.txt_confidence = QtWidgets.QLineEdit(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_confidence.sizePolicy().hasHeightForWidth())
        self.txt_confidence.setSizePolicy(sizePolicy)
        self.txt_confidence.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_top_left_x.setValidator(QIntValidator(0,999999))


        self.txt_confidence.setMaxLength(9)
        
        
        self.lyt_confidence.addWidget(self.txt_confidence)
        self.lyt_pos_info.addLayout(self.lyt_confidence)
        
        
        
        self.lyt_up_pos.addLayout(self.lyt_pos_info)
        self.lyt_main.addLayout(self.lyt_up_pos)
        self.lyt_imagenes = QtWidgets.QHBoxLayout()
        self.lyt_imagenes.setObjectName("lyt_imagenes")
        self.lyt_img_buscar = QtWidgets.QVBoxLayout()
        self.lyt_img_buscar.setObjectName("lyt_img_buscar")
        self.lbl_img_buscar = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_img_buscar.sizePolicy().hasHeightForWidth())
        self.lbl_img_buscar.setSizePolicy(sizePolicy)
        self.lbl_img_buscar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_img_buscar.setObjectName("lbl_img_buscar")
        self.lyt_img_buscar.addWidget(self.lbl_img_buscar)
        self.lw_img_buscar = QtWidgets.QListWidget(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw_img_buscar.sizePolicy().hasHeightForWidth())
        self.lw_img_buscar.setSizePolicy(sizePolicy)
        self.lw_img_buscar.setObjectName("lw_img_buscar")
        self.lyt_img_buscar.addWidget(self.lw_img_buscar)
        self.lyt_imagenes.addLayout(self.lyt_img_buscar)
        self.lyt_op_img = QtWidgets.QVBoxLayout()
        self.lyt_op_img.setContentsMargins(5, 0, 5, 0)
        self.lyt_op_img.setObjectName("lyt_op_img")
        self.btn_agregar_imagen = QtWidgets.QPushButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_agregar_imagen.sizePolicy().hasHeightForWidth())
        self.btn_agregar_imagen.setSizePolicy(sizePolicy)
        self.btn_agregar_imagen.setObjectName("btn_agregar_imagen")
        self.lyt_op_img.addWidget(self.btn_agregar_imagen)
        self.btn_remover_imagen = QtWidgets.QPushButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remover_imagen.sizePolicy().hasHeightForWidth())
        self.btn_remover_imagen.setSizePolicy(sizePolicy)
        self.btn_remover_imagen.setObjectName("btn_remover_imagen")
        self.lyt_op_img.addWidget(self.btn_remover_imagen)
        self.rb_activado = QtWidgets.QRadioButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_activado.sizePolicy().hasHeightForWidth())
        self.rb_activado.setSizePolicy(sizePolicy)
        self.rb_activado.setObjectName("rb_activado")
        self.rb_activado.setEnabled(False)
        self.lyt_op_img.addWidget(self.rb_activado)
        self.Subir_imagen = QtWidgets.QPushButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Subir_imagen.sizePolicy().hasHeightForWidth())
        self.Subir_imagen.setSizePolicy(sizePolicy)
        self.Subir_imagen.setObjectName("Subir_imagen")
        self.lyt_op_img.addWidget(self.Subir_imagen)
        self.btn_cambiar_nombre = QtWidgets.QPushButton(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cambiar_nombre.sizePolicy().hasHeightForWidth())
        self.btn_cambiar_nombre.setSizePolicy(sizePolicy)
        self.btn_cambiar_nombre.setObjectName("btn_cambiar_nombre")
        self.lyt_op_img.addWidget(self.btn_cambiar_nombre)
        self.btn_stop_all = QtWidgets.QPushButton(parent=Buscador)
        self.btn_stop_all.setObjectName("btn_stop_all")
        self.lyt_op_img.addWidget(self.btn_stop_all)
        self.lyt_imagenes.addLayout(self.lyt_op_img)
        self.lyt_img_guardadas = QtWidgets.QVBoxLayout()
        self.lyt_img_guardadas.setObjectName("lyt_img_guardadas")
        self.lbl_img_guardadas = QtWidgets.QLabel(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_img_guardadas.sizePolicy().hasHeightForWidth())
        self.lbl_img_guardadas.setSizePolicy(sizePolicy)
        self.lbl_img_guardadas.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_img_guardadas.setObjectName("lbl_img_guardadas")
        self.lyt_img_guardadas.addWidget(self.lbl_img_guardadas)
        self.lw_img_guardadas = QtWidgets.QListWidget(parent=Buscador)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lw_img_guardadas.sizePolicy().hasHeightForWidth())
        self.lw_img_guardadas.setSizePolicy(sizePolicy)
        self.lw_img_guardadas.setObjectName("lw_img_guardadas")
        # Set up a QFileSystemWatcher to monitor the folder
        self.watcher = QFileSystemWatcher(Buscador)
        self.watcher.directoryChanged.connect(self.funciones.cambios_carpeta_imagen)
        self.watcher.addPath(img_path) 
        self.lw_img_guardadas.clear()
        self.lw_img_guardadas.addItems(file_names)  

        self.lyt_img_guardadas.addWidget(self.lw_img_guardadas)
        
        #self.lw_img_guardadas.setModel(self.img_saved_model)

        self.lyt_imagenes.addLayout(self.lyt_img_guardadas)
        self.lyt_main.addLayout(self.lyt_imagenes)
        self.gridLayout.addLayout(self.lyt_main, 0, 0, 1, 1)
        self.lbl_nombre.setBuddy(self.txt_nombre)
        self.lbl_top_left_inicial.setBuddy(self.txt_top_left_x)
        self.lbl_top_leftx.setBuddy(self.txt_top_left_x)
        self.lbl_top_lefty.setBuddy(self.txt_top_left_y)
        self.lbl_bot_right_final.setBuddy(self.txt_bot_right_x)
        self.lbl_bot_rightx.setBuddy(self.txt_bot_right_x)
        self.lbl_bot_righty.setBuddy(self.txt_bot_right_y)

        self.retranslateUi(Buscador)
        self.btn_add_pos.clicked.connect(self.funciones.add_pos) # type: ignore
        self.btn_mod_pos.clicked.connect(self.funciones.mod_pos) # type: ignore
        self.btn_agregar_imagen.clicked.connect(self.funciones.add_img) # type: ignore
        self.btn_remover_imagen.clicked.connect(self.funciones.rem_img) # type: ignore
        self.Subir_imagen.clicked.connect(self.funciones.subir_img) # type: ignore
        self.btn_cambiar_nombre.clicked.connect(self.funciones.mod_img_nombre) # type: ignore
        self.cb_posicion.currentIndexChanged['int'].connect(self.funciones.cambio_espacio) # type: ignore
        #self.lw_img_buscar.addItem("asd")
        self.rb_activado.clicked.connect(self.funciones.activar) # type: ignore
        self.btn_stop_all.clicked.connect(self.funciones.stop_all) # type: ignore
        self.btn_remover.clicked.connect(self.funciones.remover) # type: ignore
        self.btn_inicial.clicked.connect(lambda: self.funciones.mouse_store_start(0)) # type: ignore
        self.btn_final.clicked.connect(lambda: self.funciones.mouse_store_start(1)) # type: ignore
        self.txt_top_left_x.textChanged.connect(self.funciones.check_txt_empty)
        self.txt_top_left_y.textChanged.connect(self.funciones.check_txt_empty)
        self.txt_bot_right_x.textChanged.connect(self.funciones.check_txt_empty)
        self.txt_bot_right_y.textChanged.connect(self.funciones.check_txt_empty)
        self.txt_confidence.textChanged.connect(self.funciones.check_txt_empty)
        QtCore.QMetaObject.connectSlotsByName(Buscador)
        Buscador.setTabOrder(self.txt_nombre, self.txt_top_left_x)
        Buscador.setTabOrder(self.txt_top_left_x, self.txt_bot_right_x)
        Buscador.setTabOrder(self.txt_bot_right_x, self.txt_top_left_y)
        Buscador.setTabOrder(self.txt_top_left_y, self.txt_bot_right_y)
        Buscador.setTabOrder(self.txt_bot_right_y, self.btn_add_pos)
        Buscador.setTabOrder(self.btn_add_pos, self.btn_mod_pos)
        Buscador.setTabOrder(self.btn_mod_pos, self.btn_remover)
        Buscador.setTabOrder(self.btn_remover, self.cb_posicion)
        Buscador.setTabOrder(self.cb_posicion, self.btn_agregar_imagen)
        Buscador.setTabOrder(self.btn_agregar_imagen, self.btn_remover_imagen)
        Buscador.setTabOrder(self.btn_remover_imagen, self.rb_activado)
        Buscador.setTabOrder(self.rb_activado, self.Subir_imagen)
        Buscador.setTabOrder(self.Subir_imagen, self.btn_cambiar_nombre)
        Buscador.setTabOrder(self.btn_cambiar_nombre, self.btn_stop_all)
        Buscador.setTabOrder(self.btn_stop_all, self.lw_img_buscar)
        Buscador.setTabOrder(self.lw_img_buscar, self.lw_img_guardadas)
        Buscador.setTabOrder(self.lw_img_guardadas, self.txtno_top_left_x)
        Buscador.setTabOrder(self.txtno_top_left_x, self.txtno_top_left_y)
        Buscador.setTabOrder(self.txtno_top_left_y, self.txtno_bot_right_x)
        Buscador.setTabOrder(self.txtno_bot_right_x, self.txtno_bot_right_y)
        Buscador.setTabOrder(self.txtno_bot_right_y, self.btn_inicial)
        Buscador.setTabOrder(self.btn_inicial, self.btn_final)
        Buscador.setTabOrder(self.btn_final, self.txt_confidence)
    
    def retranslateUi(self, Buscador):
    
        _translate = QtCore.QCoreApplication.translate
        Buscador.setWindowTitle(_translate("Buscador", "Buscador Imagenes - Lucas Silva"))
        self.cb_posicion.setCurrentText(_translate("Buscador", "Inicial"))
        self.cb_posicion.setItemText(0, _translate("Buscador", "Inicial"))
        self.cb_posicion.setItemText(self.cb_posicion.currentIndex(),self.funciones.lista_nombres[self.cb_index]+"     "+str(self.funciones.lista_posiciones[self.cb_index][0])+" "+str(self.funciones.lista_posiciones[self.cb_index][1])+" "+str(self.funciones.lista_posiciones[self.cb_index][2])+" "+str(self.funciones.lista_posiciones[self.cb_index][3]))

        self.lblno_top_left_inicial.setText(_translate("Buscador", "Inicial"))
        self.lblno_top_leftx.setText(_translate("Buscador", "x"))
        self.txtno_top_left_x.setText(_translate("Buscador", "0"))
        self.lblno_top_lefty.setText(_translate("Buscador", "y"))
        self.txtno_top_left_y.setText(_translate("Buscador", "0"))
        self.lblno_bot_right_final.setText(_translate("Buscador", "Final  "))
        self.lblno_bot_rightx.setText(_translate("Buscador", "x"))
        self.txtno_bot_right_x.setText(_translate("Buscador", "1366"))
        self.lblno_bot_righty.setText(_translate("Buscador", "y"))
        self.txtno_bot_right_y.setText(_translate("Buscador", "768"))
        self.btn_add_pos.setText(_translate("Buscador", "Añadir espacio"))
        self.btn_mod_pos.setText(_translate("Buscador", "Modificar"))
        self.btn_remover.setText(_translate("Buscador", "Remover"))
        self.lbl_nombre.setText(_translate("Buscador", "Nombre"))
        self.lbl_top_left_inicial.setText(_translate("Buscador", "Inicial"))
        self.lbl_top_leftx.setText(_translate("Buscador", "x"))
        self.txt_top_left_x.setText(_translate("Buscador", "0"))
        self.lbl_top_lefty.setText(_translate("Buscador", "y"))
        self.txt_top_left_y.setText(_translate("Buscador", "0"))
        self.lbl_bot_right_final.setText(_translate("Buscador", "Final  "))
        self.lbl_bot_rightx.setText(_translate("Buscador", "x"))
        self.txt_bot_right_x.setText(_translate("Buscador", "1366"))
        self.lbl_bot_righty.setText(_translate("Buscador", "y"))
        self.txt_bot_right_y.setText(_translate("Buscador", "768"))
        self.lbl_img_buscar.setText(_translate("Buscador", "Imagenes a buscar"))
        self.btn_agregar_imagen.setText(_translate("Buscador", "Agregar +"))
        self.btn_remover_imagen.setText(_translate("Buscador", "Remover -"))
        self.rb_activado.setText(_translate("Buscador", "Activado"))
        self.Subir_imagen.setText(_translate("Buscador", "Subir imagen"))
        self.btn_cambiar_nombre.setText(_translate("Buscador", "Cambiar nombre"))
        self.btn_stop_all.setText(_translate("Buscador", "Parar Todo"))
        self.lbl_img_guardadas.setText(_translate("Buscador", "Imagenes guardadas"))
        self.lbl_confidence.setText(_translate("Buscador", "Similitud (0.0 - 1.0)"))
        self.txt_confidence.setText(_translate("Buscador", "0.9"))
        self.lblno_confidence.setText(_translate("Buscador", "Similitud (0.0 - 1.0)"))
        self.txtno_confidence.setText(_translate("Buscador", "0.9"))